[package]
name = "bitcoin-block-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.2"
anyhow = "1.0.86"
threadpool = "1.8.1"
rustc-hash = "2.0.0"
# Could make the following deps into features
postcard = { version = "1.0.10", features = ["use-std"] }
scalable_cuckoo_filter = { version = "0.3.2", features = ["serde_support"] }
clap = { version = "4.5.16", features = ["derive"] }